### ISSUE TITLE
vue3 support not there

### ISSUE THREAD

**Issue by safikskh** [syncfusion/ej2-vue-samples#26]
I have install grid with 19.2.44  but it is not working. Also the sample is in vue 2.

**Comment by praveenkumargspr** [comment]
Hi shafik,
Greetings from Syncfusion support.

We are not able to clearly understand your reported problem from the provided information, So we need the following details to understand the query better at our end. So kindly share the following details. 
1.	Complete Grid code example.
2.	Video demonstration to understand your reported issue better at our end.
3.	Please elaborate on your exact issue scenario with more details based on which we will check from our end and provide the further details.

Please get back to us with the requested details which will be helpful for us to validate the reported scenario at our end and provide the solution as early as possible

Regards
Praveenkumar G

**Comment by gsumankumar** [comment]
We have closed this issue, since there's no recent activities. You can reopen it, if you still facing the reported problem.
