### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by jparish3** [syncfusion/ej2-vue-samples#7]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@syncfusion%2fej2-build - Not found
npm ERR! 404
npm ERR! 404  '@syncfusion/ej2-build@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ej2-vue-samples'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by Mydeen-SN** [comment]
Hi @jparish3 ,

We have resolved the missing dependency issue in the samples.

Thanks,
Mydeen

**Comment by gsumankumar** [comment]
We have closed this issue now, since there are no recent activities. Still if you have face the reported issue, please feel free to reopen it.
