### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by rogerhendriks** [syncfusion/ej2-vue-samples#9]
Repro path:
- checked out with github desktop. 
- opened cmd on W10
- cd directory
- npm install > this was my output / just warnings
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ej2-vue-samples@1.0.0 No repository field.
npm WARN ej2-vue-samples@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 16566 packages in 11.061s
found 17 vulnerabilities (1 low, 6 moderate, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details

- npm run build **hangs** on:
> ej2-vue-samples@1.0.0 build C:\Users\dev\Documents\GitHub\ej2-vue-samples
> node --max_old_space_size=8096 node_modules/webpack/bin/webpack.js --config ./webpack.config.js

>> no output? no info in readme.

**Comment by jesusarockias** [comment]
Hi @rogerhendriks ,

Sorry for the inconvenience caused.

This is a known problem and the sample number in the sample browser is the reason for this. We have already planned to fix this in our upcoming release of Volume 2, 2019, scheduled for the end of June.

We appreciate your patience until then and get back to us if you need further assistance on this.

Regards,
Jesus Arockia Sankaran S

**Comment by ghost** [comment]
Hi @rogerhendriks,

Sorry for the delay caused,

We have resolved your reported warning at our end. So, we are suggesting you use our latest version packages to avail those changes. Run the below command to install the latest version of our packages in your project. 

`npm install -g npm-check-updates`

`npm update`

**https://ej2.syncfusion.com/vue/documentation/common/how-to/update-npm-package/**

Regards,
Gokul
